level_0 = {
		'terrain': '../levels/0/level_0_terrain.csv',
		'coins':'../levels/0/level_0_coins.csv',
		'fg palms':'../levels/0/level_0_fg_palms.csv',
		'bg palms':'../levels/0/level_0_bg_palms.csv',
		'crates': '../levels/0/level_0_crates.csv',
		'enemies':'../levels/0/level_0_enemies.csv',
		'constraints':'../levels/0/level_0_constraints.csv',
		'player': '../levels/0/level_0_player.csv',
		'grass': '../levels/0/level_0_grass.csv',
		'node_pos': (110,100),
		'unlock': 1,
		'node_graphics': '../graphics/overworld/0',
		'level_bg_music': '../audio/level_music.wav',
		'flies': 2,
		'dragonflies': 0,
		'wasps': 0,
		'flies_hard': 1,
		'dragonflies_hard': 1,
		'wasps_hard': 2,
		'parachute_frog': 0,
		'parachute_frog_hard': 0,
		'goal_image': '../graphics/misc/sad_frog.png',
		'player_image': 'default'}
level_1 = {
		'terrain': '../levels/1/level_1_terrain.csv',
		'coins':'../levels/1/level_1_coins.csv',
		'fg palms':'../levels/1/level_1_fg_palms.csv',
		'bg palms':'../levels/1/level_1_bg_palms.csv',
		'crates': '../levels/1/level_1_crates.csv',
		'enemies':'../levels/1/level_1_enemies.csv',
		'constraints':'../levels/1/level_1_constraints.csv',
		'player': '../levels/1/level_1_player.csv',
		'grass': '../levels/1/level_1_grass.csv',
		'node_pos': (300,270),
		'node_graphics': '../graphics/overworld/1',
		'unlock': 2,
		'level_bg_music': '../audio/magnetic_b-ing.mp3',
		'flies': 20,
		'dragonflies': 1,
		'wasps': 0,
		'flies_hard': 20,
		'dragonflies_hard': 1,
		'wasps_hard': 4,
		'parachute_frog': 0,
		'parachute_frog_hard': 0,
		'goal_image': '../graphics/misc/sandwich.png',
		'player_image': 'default'}
level_2 = {
		'terrain': '../levels/2/level_2_terrain.csv',
		'coins':'../levels/2/level_2_coins.csv',
		'fg palms':'../levels/2/level_2_fg_palms.csv',
		'bg palms':'../levels/2/level_2_bg_palms.csv',
		'crates': '../levels/2/level_2_crates.csv',
		'enemies':'../levels/2/level_2_enemies.csv',
		'constraints':'../levels/2/level_2_constraints.csv',
		'player': '../levels/2/level_2_player.csv',
		'grass': '../levels/2/level_2_grass.csv',
		'node_pos': (350,400),
		'node_graphics': '../graphics/overworld/2',
		'unlock': 3,
		'level_bg_music': '../audio/level_music.wav',
		'flies': 10,
		'dragonflies': 3,
		'wasps': 5, 
		'flies_hard': 33,
		'dragonflies_hard': 30,
		'wasps_hard': 17,
		'parachute_frog': 0,
		'parachute_frog_hard': 0,
		'goal_image': '../graphics/character/hat.png',
		'player_image': 'sandwich'}
level_3 = {
		'terrain': '../levels/3/level_3_terrain.csv',
		'coins':'../levels/3/level_3_coins.csv',
		'fg palms':'../levels/3/level_3_fg_palms.csv',
		'bg palms':'../levels/3/level_3_bg_palms.csv',
		'crates': '../levels/3/level_3_crates.csv',
		'enemies':'../levels/3/level_3_enemies.csv',
		'constraints':'../levels/3/level_3_constraints.csv',
		'player': '../levels/3/level_3_player.csv',
		'grass': '../levels/3/level_3_grass.csv',
		'node_pos': (430,610),
		'node_graphics': '../graphics/overworld/3',
		'unlock': 4,
		'level_bg_music': '../audio/magnetic_b-ing.mp3',
		'flies': 5,
		'dragonflies': 1,
		'wasps': 0,
		'flies_hard': 10,
		'dragonflies_hard': 2,
		'wasps_hard': 1,
		'parachute_frog': 0,
		'parachute_frog_hard': 0,
		'goal_image': '../graphics/character/hat.png',
		'player_image': 'default'}
level_4 = {
		'terrain': '../levels/4/level_4_terrain.csv',
		'coins':'../levels/4/level_4_coins.csv',
		'fg palms':'../levels/4/level_4_fg_palms.csv',
		'bg palms':'../levels/4/level_4_bg_palms.csv',
		'crates': '../levels/4/level_4_crates.csv',
		'enemies':'../levels/4/level_4_enemies.csv',
		'constraints':'../levels/4/level_4_constraints.csv',
		'player': '../levels/4/level_4_player.csv',
		'grass': '../levels/4/level_4_grass.csv',
		'node_pos': (610,350),
		'node_graphics': '../graphics/overworld/4',
		'unlock': 5,
		'level_bg_music': '../audio/level_music.wav',
		'flies': 10,
		'dragonflies': 2,
		'wasps': 0,
		'flies_hard': 20,
		'dragonflies_hard': 10,
		'wasps_hard': 10,
		'parachute_frog': 0,
		'parachute_frog_hard': 0,
		'goal_image': '../graphics/character/hat.png',
		'player_image': 'default'}
level_5 = {
		'terrain': '../levels/2/level_2_terrain.csv',
		'coins':'../levels/2/level_2_coins.csv',
		'fg palms':'../levels/2/level_2_fg_palms.csv',
		'bg palms':'../levels/2/level_2_bg_palms.csv',
		'crates': '../levels/2/level_2_crates.csv',
		'enemies':'../levels/2/level_2_enemies.csv',
		'constraints':'../levels/2/level_2_constraints.csv',
		'player': '../levels/2/level_2_player.csv',
		'grass': '../levels/2/level_2_grass.csv',
		'node_pos': (880,110),
		#'node_pos': (1050,400),
		'node_graphics':'../graphics/overworld/5',
		'unlock': 5,
		'level_bg_music': '../audio/magnetic_b-ing.mp3',
		'flies': 10,
		'dragonflies': 2,
		'wasps': 0,
		'flies_hard': 20,
		'dragonflies_hard': 10,
		'wasps_hard': 10,
		'parachute_frog': 0,
		'parachute_frog_hard': 0,
		'goal_image': '../graphics/character/hat.png',
		'player_image': 'default'}
level_6 = {
		'terrain': '../levels/2/level_2_terrain.csv',
		'coins':'../levels/2/level_2_coins.csv',
		'fg palms':'../levels/2/level_2_fg_palms.csv',
		'bg palms':'../levels/2/level_2_bg_palms.csv',
		'crates': '../levels/2/level_2_crates.csv',
		'enemies':'../levels/2/level_2_enemies.csv',
		'constraints':'../levels/2/level_2_constraints.csv',
		'player': '../levels/2/level_2_player.csv',
		'grass': '../levels/2/level_2_grass.csv',
		'node_pos': (930,300),
		'node_graphics':'../graphics/overworld/5',
		'unlock': 5,
		'level_bg_music': '../audio/magnetic_b-ing.mp3',
		'flies': 10,
		'dragonflies': 2,
		'wasps': 0,
		'flies_hard': 20,
		'dragonflies_hard': 10,
		'wasps_hard': 10,
		'parachute_frog': 0,
		'parachute_frog_hard': 0,
		'goal_image': '../graphics/character/hat.png',
		'player_image': 'default'}
level_7 = {
		'terrain': '../levels/2/level_2_terrain.csv',
		'coins':'../levels/2/level_2_coins.csv',
		'fg palms':'../levels/2/level_2_fg_palms.csv',
		'bg palms':'../levels/2/level_2_bg_palms.csv',
		'crates': '../levels/2/level_2_crates.csv',
		'enemies':'../levels/2/level_2_enemies.csv',
		'constraints':'../levels/2/level_2_constraints.csv',
		'player': '../levels/2/level_2_player.csv',
		'grass': '../levels/2/level_2_grass.csv',
		'node_pos': (1050,560),
		'node_graphics':'../graphics/overworld/5',
		'unlock': 5,
		'level_bg_music': '../audio/magnetic_b-ing.mp3',
		'flies': 10,
		'dragonflies': 2,
		'wasps': 0,
		'flies_hard': 20,
		'dragonflies_hard': 10,
		'wasps_hard': 10,
		'parachute_frog': 0,
		'parachute_frog_hard': 0,
		'goal_image': '../graphics/character/hat.png',
		'player_image': 'default'}

levels = {
	0: level_0,
	1: level_1,
	2: level_2,
	3: level_3,
	4: level_4,
	5: level_5,
	6: level_6,
	7: level_7}